config/routes.rb
Rails.application.routes.draw do
  
  devise_for :buyers

  resources :contents
  devise_for :users
  
  root 'pages#home'

  get 'about' => 'pages#about'

  post '/buy/:slug', to: 'transactions#create', as: :buy

  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :content
end

app/models/content.rb
class Content < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :user
	belongs_to :category

	has_many :purchases

  	has_attached_file :copertina, styles: { large: "500x>", medium: "300x>", thumb: "100x>" } 
  	validates_attachment_content_type :copertina, content_type: /\Aimage\/.*\Z/

  	validates_presence_of :title, :tagline, :description, :price, :team, :equity, :copertina, :on => :create, :message => "can't be blank", class: "error"
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

	before_create :generate_guid
	belongs_to :content

	include AASM

	aasm column: 'state' do
		state :sleeping, :initial => true
    	state :running, :completed, :errored

    	event :running, after: :charge_card do
    		transitions from: :sleeping, to: :running
    	end

    	event :complete do
    		transitions from: :running, to: :completed
    	end

    	event :fail do 
    		transitions from: :running, to: :errored
    	end

	end

	def charge_card

		begin
			save!
			charge = Stripe::Charge.create(
				amount: self.amount,
				currency: "usd",
				card: self.stripe_token,
				description: "Content publishing"
				)
			self.update(stripe_id: charge.id)
			self.complete!

		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!
		end

	end

	private

		def generate_guid 
			self.guid = SecureRandom.uuid()
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contents

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])

  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]


  def index
    @contents = Content.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 16)
  end

  def show
  end

  def new
    @content = current_user.contents.build

  end

  def edit
  end

  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :tagline, :description, :price, :team, :equity, :website, :linkedin, :copertina)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: "We're sorry, but you don't have access to this item"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end
  	 
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def create
		content = Content.find_by!(slug: params[:slug])
		purchase = content.purchases.create(
			amount: (content.price * 100).floor,
			email_client: current_user.email,
			email: content.user.email,
			stripe_token: params[:stripeToken] 
			)
		purchase.running!

		if purchase.completed?

	  		redirect_to pickup_url(guid: purchase.guid)
	  	else

	  		redirect_to content_path(content), notice: @error
	  	end

	end

	def pickup
		@purchase = Purchase.find_by!(guid: params[:guid])
		@content = @purchase.content
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<div class="row">
    <%= simple_form_for @content, html: { multipart: true } do |f| %> 
      <div class="field">
        <%= f.input :title, required: true, class: "field" %>
        <%= f.input :tagline, required: true, label: 'Short description', input_html: { maxlength: 50 }, class: "field" %>
        <%= f.input :description, required: true, as: :text, class: "field" %>
        <%= f.input :price, required: true, class: "field" %>
        <%= f.input :team, required: true, label: 'Team member number', class: "field" %>
        <%= f.input :equity, required: true, label: 'Equity percentage', class: "field" %>
        <%= f.input :website, label: 'Website Link', as: :string, class: "field" %>
        <%= f.input :linkedin, label: 'Linkedin Link', as: :string, class: "field" %>
        
        <br>
        <label>Upload a cover image of your project (.jpeg, .jpg)</label>
        <div class="image-field">
            <%= f.input :copertina, required: true, label: false %>
        </div>
        <br>
        <%= f.button :submit, class: "btn btn-devise waves-effect waves-light blue accent-3" %>
      </div>
    <% end %>
</div>

app/views/contents/edit.html.erb
<h4 class="center blue-text text-accent-3">Edit <%= @content.title %></h4>

<%= render 'form' %>

<%= link_to 'Show your content', @content %> |
<%= link_to 'Back to contents', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Listing Contents</h1> -->

 <div class="row">
  <% @contents.each do |content| %>
    <div class="col s3">
      <div class="card">
        <div class="card-image">
          <%= image_tag content.copertina.url %>
        </div>
        <div class="card-content">
          <span class="card-title activator"><%= content.title %></span>
          <p class="tagline"><%= content.tagline %></p>
        </div>
        <div class="card-content">
          <span>By <%= content.user.name %></span>
          <br>
          <span class:"left"><%= number_to_currency(content.price) %></span>
        </div>
        <div class="card-action">
          <div class="center-align"><%= link_to 'Show More', content, class: "btn btn-devise waves-effect waves-light blue accent-3" %></div>
          <% if content.user == current_user %>
          <br>
            <div class="center-align">
              <%= link_to 'Edit', edit_content_path(content), class: "blue-text text-accent-3"%>
              <%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' }, class: "red-text" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<div class="pag center">
  <%= will_paginate @contents, renderer: MaterializePagination::Rails %>
</div>

app/views/contents/index.js.erb
$('#contents').append('<%= j render()@contents %>');
<%= if @contents.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@contents) %>');
<%= else %>
	$('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/contents/new.html.erb
<h4 class="center blue-text text-accent-3">Add a project</h4>

<br>

<%= render 'form' %>

<br>

<%= link_to 'Back to contents', contents_path %>

app/views/contents/show.html.erb
<div class="row">
	<p class="center-align title">
		  <%= @content.title %>
	</p>

	<p class="center-align">
		  by user
	</p>

	<br>

	<div class="sidebar col s12 m4 l3">
        <div class="panel">
          	<p class="info center-align">
				Info:
			</p>

			<p class="left-align">
			  Equity: <%= @content.equity %>%
			</p>

			<div class="divider"></div>

			<p class="left-align">
			  Team members: <%= @content.team %>
			</p>

			<div class="divider"></div>

			<p class="left-align">
			  Website: <br><%= @content.website %>
			</p>

			<div class="divider"></div>

			<p class="left-align">
			  Linkedin: <br><%= @content.linkedin %>
			</p>

			<div class="divider"></div>
        </div>
	</div>

	<div class="col s12 m8 l9">
			<div class="center-align">
				<%= image_tag @content.copertina.url(:large)%>
			</div>

			<p class="center-align">
			  <strong>Description:</strong>
			  <%= @content.description %>
			</p>

			<p class="center-align">
			  <strong>Price:</strong>
			  <%= number_to_currency(@content.price) %>
			</p>

			<p>
				<% if current_user %>
					<%= form_tag buy_path(slug: @content.slug) do %>
						<script
						    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
						    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
						    data-amount="<%= (@content.price * 100).floor %>"
						    data-name="Starthia"
						    data-description="<%= @content.title %>"
						    data-email="<%= current_user.email %>"
						    data-image="/img/dollar-symbol.png"
						    data-locale="auto"
						    data-zip-code="true"
						    data-currency="usd">
						</script>
					<% end %>
				<% else %>
					<p>You have to be <%= link_to "Logged In", new_user_session_path, class: "blue-text text-accent-3" %> to buy.</p>
				<% end %>
			</p>
			
			<div class="center">
		        <div class="textholder white-text">
		          	<p class="center-align">
			  			<strong>Contact email: <%= @content.contact %></strong>
					</p>
		        </div>
		    </div>

			<br>

			<% if @content.user == current_user %>
				<%= link_to 'Edit your content', edit_content_path(@content) %> |
			<% end %>
			<%= link_to 'Back to contents', contents_path %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer white">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4 blue-text text-accent-3">
          © 2016 $TARTHIA
        </div>
        <div class="col s4 blue-text text-accent-3 center">
          Social
        </div>  
        <div class="col s4">
          <%= link_to 'About', about_path, class: "blue-text text-accent-3 right" %>
        </div>
        <div>Icons made by <a href="http://www.flaticon.com/authors/gregor-cresnar" title="Gregor Cresnar">Gregor Cresnar</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
	<nav class="white">
	    <div class="container nav-wrapper">
	      <%= link_to '$ T A R T H I A', root_path, class: "brand-logo blue-text text-accent-3" %>
	      <a href="#" data-activates="mobile-demo" class="button-collapse blue-text text-accent-3"><i class="material-icons">menu</i></a>
	      <ul class="right hide-on-med-and-down">
	      	<li><%= link_to 'Add a project', new_content_path, class: "blue-text text-accent-3" %></li>
	      	<% if user_signed_in? %>
	      		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "blue-text text-accent-3"%>
	      		</li>
	      	<% else %>
		      	<li><%= link_to "Log In", new_user_session_path, class: "blue-text text-accent-3" %>
		      	</li>
		      	<li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-devise waves-effect waves-light blue accent-3" %>
		      	</li>
		    <% end %>  	
	      </ul>
	      <ul class="side-nav" id="mobile-demo">
	      	<li><%= link_to 'Add a project', new_content_path, class: "blue-text text-accent-3" %></li>
	        <% if user_signed_in? %>	
	      		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "blue-text text-accent-3" %>
	      		</li>
	      	<% else %>
		      	<li><%= link_to "Log In", new_user_session_path, class: "blue-text text-accent-3" %>
		      	</li>
		      	<li><%= link_to "Sign Up", new_user_registration_path, class: "blue-text text-accent-3" %>
		      	</li>
		    <% end %> 
	      </ul>
	    </div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Starthia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body>

<%= render "layouts/header" %>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<main class="container">
	<%= yield %>
</main>

<%= render "layouts/footer" %>

</body>
	<script>
		$(".button-collapse").sideNav();
	</script>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>Starthia is made by a guy based in London while attending the International Baccalaureate at ACS Cobham.</p>

app/views/pages/home.html.erb
<div class="row">
	<div class=" home center">

		<h1 class="blue-text text-accent-3">$ T A R T H I A</h1>
		<h3 class="blue-text text-accent-3">Where Startup meet Investor</h3>

		<br>
		<br>
			
		<%= link_to "For Startup", new_user_registration_path, class: "col l4 offset-l1 btn btn-devise waves-effect waves-light blue accent-3" %>
      	<%= link_to "For Investor", new_user_registration_path, class: "col l4 offset-l2 btn btn-devise waves-effect waves-light blue accent-3" %>

      	<br>
      	<br>
      	<br>
      	<br>

      	<div class="service">
      		<div class="col s4">
	            <div class="icon-block">
	              <h2 class="center blue-text text-accent-3"><i class="fa fa-universal-access"></i></h2>
	              <h5 class="center">Join a community full of people with big ideas</h5>
	              <br>
	              <h6 class="paragraph center">Everyone can join this movement, start chatting with people that think like you and don't forget to share it with your friends.</h6>
	            </div>
		    </div>
	      	<div class="col s4">
		        <div class="icon-block">
	              <h2 class="center blue-text text-accent-3"><i class="fa fa-money"></i></h2>
	              <h5 class="center">Find your new investor and develop your ideas</h5>
	              <br>
	              <h6 class="paragraph center">Start to think like us and get ready to change the world to a better one.</h6>
	            </div>
	      	</div>
		    <div class="col s4">
		        <div class="icon-block">
	              <h2 class="center blue-text text-accent-3"><i class="fa fa-rocket"></i></h2>
	              <h5 class="center">Invest in the next money maker startup</h5>
	              <br>
	              <h6 class="paragraph center">Already al lot of people change their mind, now it's your turn. Join us for free forever.</h6>
	            </div>
	            <br>
		      	<br>
	      	</div>
      	</div>

      	<div class="back-to-top">
      		<a class="btn-floating btn-large waves-effect waves-light blue accent-3 right" href="#top"><i class="fa fa-arrow-up"></i></a>
      	</div>
	</div>
</div>

app/views/transactions/pickup.html.erb
<h1>Thanks for purchasing</h1>

<p>Your content has been published</p>